### ISSUE TITLE
博主您好

### ISSUE THREAD

**Issue by wu3216428** [KingArtherTT/ImageSearchV2#1]
博主您好，我觉得你们的检索系统非常棒。请问博主可以提供一下环境要求吗？我想复现做学习用，希望博主回复我：）

**Comment by KingArtherTT** [comment]
这个项目不更新了，这个项目以前用在这个比赛里面  [淘宝直播商品识别](https://tianchi.aliyun.com/competition/entrance/231772/introduction?spm=5176.12281957.J_3941670930.4.605a3b74DMPESb)   

详情可以去这个比赛官网看看好的解决方案。
